### ISSUE TITLE
Wireframes - Game startup flow

### ISSUE THREAD

**Issue by pubudu-ranasinghe** [mewan94/Stock-Market-simulation-Game#2]
- When user opens the game, he sees create new game button.
- Creating game redirects to game lobby. Shows a link he can share with friends so that others can join the same game.
- Players can add a nickname
- Use few pages/steps as much as possible
- Start game

**Comment by shansanira** [comment]
do you want me to start the UI designs with this?

**Comment by shansanira** [comment]
[https://xd.adobe.com/view/4743f20d-bb50-454a-5c4e-f0c6f5fba072-3172/?fullscreen](url)

Go to this link for see the prototype, Still working on it, let me know any changes should be done.

**Comment by mewan94** [comment]
I'm ok with designs and steps. shall we change the colour to a lighter one? a bit difficult to see

**Comment by Dilshanf3** [comment]
Went through the the prototype  its seems good .

**Comment by shansanira** [comment]
@mewan94  which colors do you suggest machan? because we have to change the entire color theme accordingly...

**Comment by shansanira** [comment]
Guys need suggestions, what information should we display in game board?

**Comment by shansanira** [comment]
https://xd.adobe.com/spec/2e80562b-4531-4e44-7ce8-77c386564f81-58b1/
Go to this link, to see the color codes, element height, width, opacity options, x and y coordinates and all.

https://www.youtube.com/watch?v=Jdp8A4Vmt4g
See this video for understanding how this work.

**Comment by mewan94** [comment]
@shansanira check this -> https://material.io/tools/color/#!/?view.left=1&view.right=0&primary.color=7B1FA2

**Comment by shansanira** [comment]
@mewan94  You suggest that using same color theme but bit lighter right... K I'll try to change those

**Comment by mewan94** [comment]
@shansanira yep :+1:

**Comment by pubudu-ranasinghe** [comment]
Looks good.

- No need to have the exit button since this is a website
- Use a better font(this looks like the default one) some suggestions are 
  - [Work Sans](https://fonts.google.com/specimen/Work+Sans)
  - [Montserrat](https://fonts.google.com/specimen/Montserrat)
  - [Lato](https://fonts.google.com/specimen/Lato)
  - [Rubik](https://fonts.google.com/specimen/Rubik)
  - I'm linking google fonts. They'd be easier to use and free
- Rather than having two game types for mutiplayer/AI, we can have one game type. In the join game page the user can add AI players and human players can also join the same game.
- In the same screen show a link generated for that game. He can share the link with friends so that they can join. Link would look like _stockmania.com/5c4ea3_
- (try removing the shadow in the wave. since everything is flat design, removing the shadow might look better) ;)

**Comment by pubudu-ranasinghe** [comment]
@shansanira any improvements on my suggestions? 
Also make **wireframes first before the mockup**. So we can finalize on game flow before going into mockups

**Comment by shansanira** [comment]
ya adding those to the design @pubudu-ranasinghe

**Comment by pubudu-ranasinghe** [comment]
@shansanira deadline is today?

**Comment by shansanira** [comment]
https://xd.adobe.com/view/4743f20d-bb50-454a-5c4e-f0c6f5fba072-3172/?fullscreen

This is the link to new mock-ups. Sorry for the delay guys. All the initiating level is included, now we have to develop this and plan the game board.

**Comment by mewan94** [comment]
this is good. shall we close the issue now? @pubudu-ranasinghe @shansanira @Dilshanf3 @zl3nz3r

**Comment by shansanira** [comment]
Ya Sure
