### ISSUE TITLE
Design and plan the core game architecture

### ISSUE THREAD

**Issue by pubudu-ranasinghe** [mewan94/Stock-Market-simulation-Game#3]
Draw architecture diagrams

**Comment by pubudu-ranasinghe** [comment]
[Classes.pptx](https://github.com/mewan94/Stock-Market-simulation-Game/files/2023231/Classes.pptx)
Class structure suggested by @shansanira

**Comment by mewan94** [comment]
![483404fe-9510-4ade-ad5e-b1f50712c956](https://user-images.githubusercontent.com/14161009/40381735-2066d64a-5e1a-11e8-9bc0-5570f2f2f890.jpeg)

basic api requests

**Comment by pubudu-ranasinghe** [comment]
# 🚀 The Microservices Architecture

![mars-architecture](https://user-images.githubusercontent.com/3397619/40586267-cb375c54-61dd-11e8-8140-1596ec538ce5.jpg)

During Sprint 1 and 2 our main effort will be spent on Player, Broker, Bank and Stock Market Services.
Each of these will be independent services exposing (and/or) consuming REST API endpoints.

## 📈 Stock Market
Manages games and stock market simulation
Has the ability to run concurrent games. Each _game_ is a _simulation_ containing _players_ and _stocks_

- POST /games
  - The user in the token is set as the game admin
  - Returns a gameId
- POST /games/{gameId}
  - Joins the given game
- POST /games/{gameId}/start
  - Start the game. Only admin player can do this
- GET /games/{gameId}
  - Returns current turn
- GET /games/{gameId}/stocks
  - Returns a list of stocks and their prices in the current turn

## 💰 Bank 
Manages player accounts and their money
An account will have a balance and their transaction history
Transaction = turn, type(deposit/withdraw), sender/receiver, amount

- POST /player
  - Creates a new player and sends a JWT
- POST /transaction
  - Creates new transaction. Request should mention player, type and all other details
- GET /player
  - Returns account balance

## 💼 Broker

Manages players stocks, buys and sells on behalf of the player
Player account consist of portfolio and transaction history
Transaction = turn, type(buy/sell), stock, quantity, price

- POST /account
  - opens a new trading account
  - should provide gameId
- POST /transaction
  - Does buy or sell
- GET /account
  - returns portfolio of the user
- GET /stocks
  - returns stock prices list


## 🎮 Player

----

Need help refining the routes and writing a description for Player component.

This is the basic idea. Please provide your suggestions so we can mark this task complete.

@mewan94 @shansanira @Dilshanf3 @kcmeeya @zl3nz3r

**Comment by mewan94** [comment]
@pubudu-ranasinghe This is great! just one question, if we update current turn with firebase and react app directly read current turn from firebase DB, do we need a service for that? 
 I assume that the player component is 'react app'.
My suggestions for the player component are,
1. '/' : welcome screen and game menu
2. '/play' : main game interface
3. '/my-account' : player's bank account and trading account
4. '/suggestions' : reports provided by analyst
5. '/results' : scores 

any ideas?

**Comment by Dilshanf3** [comment]
When looking to the microservices Architecture it's simply awesome. 
Suggestions for the player components are 
1.instructions to play
2.home screen to guide plyer(.... /home) 
3.connect and play(play online or with machine)
(... /game/gameid)
4.check account(game/001/account) 
5.feedback(game/001/user/feedback)
6.results({game id:001 winner:username})

For the moments my suggestions are above.And simply we need to recognize what are the paramers that we are going to send to recieve outputs from backend. (suggestion for front end)

**Comment by pubudu-ranasinghe** [comment]
@mewan94 I was thinking maybe we dont need to interact with firebase at all.
I was thinking about the realtime issue, and it seems the only realtime aspect we need is syncing the clock/countdown. (correct me if I'm wrong)
This we can achieve by simply starting a clock in frontend and backend. At each turn when retrieving new stock prices the api can send `turn_start_time timestamp`. This way the clocks can be synchronized.
So the frontend might not have to interact with FB at all

@Dilshanf3 what is feedback?

**Comment by Dilshanf3** [comment]
@pubudu - updated it's not feedback it's about suggestions for players as @mewan mentioned.

**Comment by pubudu-ranasinghe** [comment]
Updated with feedback. I'll close this issue tomo. Others can provide feedback meanwhile.

**Comment by Dilshanf3** [comment]
@mewan94  Ya right we don't need to include data items with URL we can use token value.
@mewan94  its right , we can use token value with URl(as i think then we can uniquely identify the exact user and also token can be expired after few minutes or maybe refreshing the browser).
EX:- Stockmarket/tokenvalue/Play
       StockMarket/tokenvalue/account

**Comment by mewan94** [comment]
@Dilshanf3 refreshing the browser, closing the browser or time doesn't clear data saved in browser storage. these data can only be modified (or delete) by the user (manually) or domain which stored data. (the same scenario, when you go to facebook.com it automatically log in without asking password). 
but when someone shares an invitation we should add group id to shareable URL.
