### ISSUE TITLE
Design welcome screen

### ISSUE THREAD

**Issue by mewan94** [mewan94/Stock-Market-simulation-Game#7]
------------------------------------------------------------------------------------------
# Defect
------------------------------------------------------------------------------------------

## Affected Version:
Web Service Version Id:
Web Portal Version Id:
Financial Version Id:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Expected Behavior:
1.
2.
3.
4.

## Actual Behavior:
1.
2.
3.
4.

## Fixed Version:
Web Service Version Id:
Web Portal Version Id:
Financial Version Id:

## Defect leakage Reason:

------------------------------------------------------------------------------------------

# Feature  
------------------------------------------------------------------------------------------

## Estimation: 
   Story Points:
   
   
## Testing Notes:
   Areas to be specially tested

**Comment by shansanira** [comment]
https://xd.adobe.com/view/4743f20d-bb50-454a-5c4e-f0c6f5fba072-3172/?fullscreen

go to this link for the wireframe
